import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          this works pretty well
        </h1>

        <p className={styles.description}>
          Podemos usar esto para dar los cursos, sin tener que instalar nada. Se conecta con GitHub súper fácil y desde aquí mismo haces commit y todo. En resumen solo usaremos:


<h1>Te contesté pero no me viste. HARÉ UN PUSH</h1>

          <ol>
            <li>Vercel</li>
            <li>Replit</li>
            <li>GitHub</li>
          </ol>
        </p>
        <h2>oh.. </h2>

        <a href='https://test-arvindell.vercel.app/'>
          Visita esta página
        </a>
      </main>
    </div>
  )
}
